services:
  app:
    build: .
    env_file: .env
    restart: always
    networks:
      - web
    expose:
      - "3000"   # internal port your MCP bridge listens on

  caddy:
    image: caddy:2
    restart: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    external: false
